#!/bin/bash

hits=0
deviation=0
a=0
approx=0

for i in {1..10000}
do
	x=`awk -v seed=$RANDOM 'BEGIN{srand(seed);print sprintf("%.15f", rand())}'` # generate coords
	y=`awk -v seed=$RANDOM 'BEGIN{srand(seed);print sprintf("%.15f", rand())}'`
	a=`echo "$x ^ 2" | bc`
	b=`echo "$y ^ 2" | bc`
	csquared=`echo "$a + $b" | bc -l`
	c=`echo "sqrt($csquared)" | bc -l`  # calculate distance
	cond=`echo "$c<=1" | bc -l`
	if [ "$cond" -eq "1" ]; then
		hits=`expr $hits + 1`  # register hit if distance is within circle
	fi
	approx=`echo "4 * $hits / $i" | bc -l`
	dev=`echo "($approx - 3.1415926535) ^ 2" | bc -l`
	deviation=`echo "$dev + $deviation" | bc -l`  # calculate deviation
	echo -n "Point #"
	echo -n $i
	echo -n " "
	echo $approx
	a=$i
done

# display results if script completed
echo -n "Approximation: "
echo $approx
echo -n "Deviation: "
echo `echo "sqrt($deviation / $a)" | bc -l`
echo -n "% error: "

error=`echo "100 * ($approx - 3.1415926535) / 3.1415926535" | bc -l`
echo `echo "sqrt($error * $error)" | bc -l`
