#!/bin/bash

hits=0

for i in {1..10000}
do
	x=`awk -v seed=$RANDOM 'BEGIN{srand(seed);print rand()}'`
	y=`awk -v seed=$RANDOM 'BEGIN{srand(seed);print rand()}'`
	a=`echo "$x ^ 2" | bc`
	b=`echo "$y ^ 2" | bc`
	csquared=`echo "$a + $b" | bc -l`
	c=`echo "sqrt($csquared)" | bc -l`
	cond=`echo "$c<=1" | bc -l`
	if [ "$cond" -eq "1" ]; then
		hits=`expr $hits + 1`
	fi
	echo -n `echo "4 * $hits / $i" | bc -l`
	echo -n " "
	echo -n $cond
	echo -n " " 
	echo $c
done
